# Generated by Django 6.1 on 2026-09-09 08:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('internship', 'Internshipo'), ('reseach', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance')], default='freelance', max_length=20)),
                ('thumbnail', models.URLField(blank=True, max_length=255, null=True)),
                ('start_at', models.DateField(auto_now_add=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
