# Generated by Django 5.0 on 2026-09-13 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=255, null=True)),
                ('issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('date_received', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='keyfeatures',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
