# Generated by Django 5.0 on 2026-09-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_award_experience_keyfeatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='date_received',
            field=models.DateField(),
        ),
    ]
