# Generated by Django 5.0 on 2026-09-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_award_date_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
