# Generated by Django 5.0 on 2026-09-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_experience_created_at_experience_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
