# Generated by Django 6.1 on 2026-09-21

from django.db import migrations, models


def rename_research_category(apps, schema_editor):
    Experience = apps.get_model("main", "Experience")
    Experience.objects.filter(category="reseach").update(category="research")


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_experience_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="category",
            field=models.CharField(
                choices=[
                    ("internship", "Internship"),
                    ("research", "Research"),
                    ("volunteer", "Volunteer"),
                    ("part-time", "Part-Time"),
                    ("full-time", "Full-Time"),
                    ("freelance", "Freelance"),
                ],
                default="freelance",
                max_length=20,
            ),
        ),
        migrations.RunPython(rename_research_category, migrations.RunPython.noop),
    ]
