# Generated by Django 5.0 on 2026-09-28 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_experience_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_awards', to=settings.AUTH_USER_MODEL),
        ),
    ]
